<HTML>	
<HEAD>
<TITLE>«Достопримечательности России»</TITLE>
</HEAD>
<FRAMESET FRAMEBORDER=1 BORDER=2 ROWS=140,*>
<FRAME SCROLLING=no NORESIZE SRC=Name.html NAME=Neme>
<FRAMESET FRAMEBORDER=1 BORDER=2 COLS=305,*>
<FRAME SCROLLING=YES NORESIZE SRC=Menu.html NAME=Сылки>
<FRAME SCROLLING=YES NORESIZE SRC=CONT.html NAME=CONTENT>
</FRAMESET>
</FRAMESET>
</HTML>
